const firebaseConfig = {
    apiKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    authDomain: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    databaseURL:'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    projectId: "Test=1234",
    storageBucket: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    messagingSenderId: "1234567678",
    appId: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

export default firebaseConfig;